server:
  port: 8080

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

rate-limit:
  enabled: true

  rules:

    - name: login
      path: /api/v1/auth/login
      method: POST
      requests: 5
      window: 1m

    - name: register
      path: /api/v1/auth/register
      method: POST
      requests: 3
      window: 1h

    - name: refresh
      path: /api/v1/auth/refresh
      method: POST
      requests: 120
      window: 1h

    - name: logout
      path: /api/v1/auth/logout
      method: POST
      requests: 60
      window: 1h

    - name: authenticated
      path: /api/v1/**
      requests: 300
      window: 1m

resilience4j:
  circuitbreaker:
    instances:

      userService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.net.ConnectException

      authService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true